### ISSUE TITLE
Support rendering in guake terminal

### ISSUE THREAD

**Issue by williamdes** [lusingander/serie#11]
https://github.com/Guake/guake

On Guake terminal only the graph does not render, it leaves a blank space

**Comment by lusingander** [comment]
Does Guake support any image display protocols? If not, of course, there is nothing we can do.

**Comment by williamdes** [comment]
> Does Guake support any image display protocols? If not, of course, there is nothing we can do.

Do you know a tool to test this?
I guess maybe you can glance some information from https://github.com/Guake/guake/issues/1806

**Comment by lusingander** [comment]
There is [imgcat](https://iterm2.com/documentation-images.html) for iTerm and a [sample script](https://sw.kovidgoyal.net/kitty/graphics-protocol/) for kitty.

I guess the only other thing you can do is look through the documentation or issues.

**Comment by lusingander** [comment]
I don't think it works so I'll close it.
If necessary, you may share information on the [Discussions](https://github.com/lusingander/serie/discussions/29).
