### ISSUE TITLE
Support key binds mapping

### ISSUE THREAD

**Issue by yanganto** [lusingander/serie#15]
Hi there,
Thanks for providing this, the git log view is awesome. Flexible keybinding can make this project better and more popular.

I love to work on this issue, and I also have experience with this.

- the keybinding for gitui https://github.com/extrawurst/gitui/pull/234
- the keybinding for kld https://github.com/kuutamolabs/kld/blob/main/tui/src/keybinding.rs

What I want to implement are
- [x] a vim style default keybinding
- [x] read a keybinding config then patch on the default, so the user can modify part of key binds not always all
- [x] the config is `toml`, because we already use `toml = "0.8.16"` and it will be easier to write comments in the config file

The following are possible optional features with event abstract layer
- [x] Abstract events, so the user can customize one or multiple key binds with the same event, ex `<Ctrl-c>` `<q>` for quitting app
- [x] Print help from the `Display` of an event, so the help will always be the same as the key bind to avoid typos. The typos make it possible to let the key binds document in help different from the actual key binds used and let people confuse.

Do these ideas look good to you?  If these are good, I am happy to work on them and can discuss them in the PR later.

By the way, if it is good I'd like to make the wordings with i10n, and it can be tracked in another issue.

**Comment by lusingander** [comment]
I think this is very cool.
I thought it would be a good to have this as well, but it's a lot of work so I haven't implemented it yet.

And it seems to me that the points you have given cover almost everything there is to consider. So it looks good.

> By the way, if it is good I'd like to make the wordings with i10n, and it can be tracked in another issue.

It seems like a useful feature, but we should consider whether we want to implement it right away.

At least for now, it's not a complex application and I'm not sure how many users would be interested, so I'm worried that this will become unnecessarily complicated.

**Comment by edte** [comment]
Want to support git log-like d and u movement keys

**Comment by lusingander** [comment]
> Want to support git log-like d and u movement keys

Are you referring to using a pager such as `less` rather than `git log`? Is `Ctrl-d/u` not enough?

**Comment by yanganto** [comment]
Hi @edte 
The following is the example you can have `ctrl-u` and `ctrl-d` key inputs as you wish with this PR.

1. Save the following keys in a toml file.

```toml
NavigateUp = ["ctrl-u"]
NavigateDown = ["ctrl-d"]
```
2. `$ mkdir ~/.config/serie`

3. creat `~/.config/serie/config.toml` with following format
```toml
custom_keybind_path = "/full/path/to/the/patch/file/in/step/1"
```

I already tested these steps, if you have any bad user experience please let me know, we can make this better. :smile:

**Comment by edte** [comment]
> > 想要支持类似 git log 的 d 和 u 移动键
> 
> 您是指使用诸如 `less` 类的寻呼机而不是 `git log` 吗？ `Ctrl-d/u` 还不够吗？@edte

Yes, u and d are aliases of ctrl-u and ctrl-d, I think these two are more convenient



> 你好@edte以下是您可以根据需要使用 `ctrl-u` 和 `ctrl-d` 键输入的示例 #21 。
> 
> 1. `$ mkdir ~/.config/serie`
> 2. 使用以下内容创建 `~/.config/serie/config.toml`
> 
> ```toml
> [custom_keybind_patch]
> NavigateUp = ["ctrl-u"]
> NavigateDown = ["ctrl-d"]
> ```
> 
> 我已经测试了这些步骤，如果您有建议，请告诉我，我们可以做得更好。 😄

My configuration doesn't seem to work
```
[custom_keybind_patch]
NavigateUp = ["u"]
NavigateDown = ["d"]
```

**Comment by edte** [comment]
> > Want to support git log-like d and u movement keys
> 
> Are you referring to using a pager such as `less` rather than `git log`? Is `Ctrl-d/u` not enough? @edte

Yes, u and d are aliases of ctrl-u and ctrl-d, I think these two are more convenient




> Hi @edte The following is the example you can have `ctrl-u` and `ctrl-d` key inputs as you wish with #21.
> 
> 1. `$ mkdir ~/.config/serie`
> 2. create `~/.config/serie/config.toml` with the following content
> 
> ```toml
> [custom_keybind_patch]
> NavigateUp = ["ctrl-u"]
> NavigateDown = ["ctrl-d"]
> ```
> 
> I already tested these steps, if you have suggestions please let me know, and we can make this better. 😄

hello,config this like doesn't seem to work
```
[custom_keybind_patch]
NavigateUp = ["u"]
NavigateDown = ["d"]
```

**Comment by yanganto** [comment]
> hello,config this like doesn't seem to work
> 
> ```
> [custom_keybind_patch]
> NavigateUp = ["u"]
> NavigateDown = ["d"]
> ```
Hi @edte,
Please double-check that you are using binary from #21 and use `?` to see the keybind?
It works with `u` and `d` with #21.
![u-d](https://github.com/user-attachments/assets/11f6f208-9084-45b2-aabf-afe6809ef6b7)
