### ISSUE TITLE
Arch package not found

### ISSUE THREAD

**Issue by dadav** [lusingander/serie#18]
The package for archlinux does not exist anymore?

**Comment by lusingander** [comment]
#14 ?

**Comment by dadav** [comment]
Yeah, it should be there, but - at least for me - ` sudo pacman -S serie` results in a package not found error. Maybe some other archlinux user could check this..

**Comment by alerque** [comment]
@dadav Use `pacman -Sy` to update your repository indexes. If it still isn't there wait for the mirror you use to be refreshed.

**Comment by dadav** [comment]
Works now, thanks for checking.
