### ISSUE TITLE
Config directory without `$XDG_CONFIG_HOME` should default to `~/.config/...`

### ISSUE THREAD

**Issue by uncenter** [lusingander/serie#25]
I was reading through the readme and was quite surprised that if `XDG_CONFIG_HOME` is not defined the configuration directory is instead `~/.cache/`. This seems like an odd choice - `XDG_CONFIG_HOME` is typically `~/.config/` and serie should probably default to that as well.

**Comment by alerque** [comment]
Yes definitely.

**Comment by uncenter** [comment]
I think this must be a typo actually?
