### ISSUE TITLE
Neither protocol working in VSCode integrated

### ISSUE THREAD

**Issue by uncenter** [lusingander/serie#26]
https://github.com/lusingander/serie#inline-images-protocol lists the VSCode integrated terminal as supported with the `iterm` protocol, however I'm not able to see the graph with either protocol.

**Comment by alerque** [comment]
Same here with the open source `vscode` build on Linux. I suspect (but guessing, don't know) this is because the heavy lifting for the terminal widget is pawned off on something else platform specific, and on macOS that might be an embedded iTerm or something like that.

**Comment by uncenter** [comment]
I think you are right. Looking at [image protocol support for another program again, Yazi](https://github.com/sxyazi/yazi#image-preview), looks like VSCode is supposed to work with inline images - and you guessed it, somehow relating to iTerm. Not seeing Yazi's image support work in VSCode's terminal either.

**Comment by uncenter** [comment]
Ah, maybe this will help? 😃 

![CleanShot 2024-08-02 at 09 22 15@2x](https://github.com/user-attachments/assets/c0f104ad-ccc3-4fbb-802d-30b918300dc7)

**Comment by uncenter** [comment]
Yep, that did it ahah. Looks like it is disabled by default? That should be noted in the support table, https://code.visualstudio.com/docs/terminal/advanced#_image-support could be linked here as well.
