### ISSUE TITLE
Use `git`'s `--date-order` or `--topo-order` 

### ISSUE THREAD

**Issue by kdheepak** [lusingander/serie#3]
I'm sure you are already aware of this, but thought I'd mention it just to check:

https://github.com/lusingander/serie/blob/779bd6ef1465c058de590e71d6dcab91b59e93b8/src/git.rs#L239-L251

You can use `--date-order` or `--topo-order` here directly, e.g.:

```rust
    let mut cmd = Command::new("git")
        .arg("log")
        // exclude stashes and other refs
        .arg("--branches")
        .arg("--remotes")
        .arg("--tags")
        .arg(format!("--pretty={}", load_commits_format()))
        .arg(match order {
            CommitOrderType::Chrono => "--date-order",
            CommitOrderType::Topo => "--topo-order",
        })
        .arg("--date=iso-strict")
        .arg("-z") // use NUL as a delimiter
        .current_dir(path)
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
```

That way you can skip a bunch of calculation you do internally and rely on the order in git. If you do that, your graph will match closely with the output from `git log --oneline --graph`

**Comment by lusingander** [comment]
I hadn't thought about this because it was based on code I had implemented as a trial in the past 😀

That may be enough.
We may need to think about how to handle stashes, but that doesn't seem like a big problem.

**Comment by kdheepak** [comment]
I used `--all` in the PR #5 and it seems to work fine for me:

<img width="464" alt="image" src="https://github.com/user-attachments/assets/2f00cae7-4806-4dbb-abde-0f6b386fb880">

Is there a reason you opted to not do that?

**Comment by lusingander** [comment]
- The working directory change and the index change (and untracked files) are shown as separate commits, but many clients (not `git log`) combine them as one commit.
  - This is a matter of preference, but I prefer it combined.
- I don't think it would be possible to get it if there are multiple stashes.
  - It would be more useful to have all stashes shown as commits.
- Also, I think these stashes should appear just one commit above the original commit.
  - If we want to merge a stash without sorting the commits, we need to insert it in the right position.

**Comment by kdheepak** [comment]
Great points!

I don't view the graph with stashes all that much, but it does seem to match what git does at the moment:

<img width="97" alt="image" src="https://github.com/user-attachments/assets/9eaa9630-dfee-4b5d-8b0d-fd16712bb399">

**Comment by lusingander** [comment]
Yes, `git log`, `tig`, etc. will show it that way.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/3b89eabe-6adb-4bd1-9881-4cac7f04cd39"> <img width="337" alt="image" src="https://github.com/user-attachments/assets/25d36940-cf27-474c-9e62-6ade356b89b0">

For me, these client-like graphs are easier to use:

<img width="319" alt="image" src="https://github.com/user-attachments/assets/7602fe5e-d138-48fd-b4f5-c104045aa88f"> <img width="379" alt="image" src="https://github.com/user-attachments/assets/e0d2cb86-8f03-497b-a273-ba0183db445e">

**Comment by kdheepak** [comment]
What graphs are those btw? Those look quite nice.

**Comment by lusingander** [comment]
https://git-fork.com
https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph
