### ISSUE TITLE
Running `serie` on `git`'s git repo stackoverflows

### ISSUE THREAD

**Issue by kdheepak** [lusingander/serie#4]
Clone https://github.com/git/git/ and run `serie`:

<img width="279" alt="image" src="https://github.com/user-attachments/assets/a4166cb0-0d8a-43f6-b72b-39341dda060e">

It does not segfault with `tig` or `vim-flog`. LazyGit loads only 300 commits and loads more if necessary but I think it should be fast enough to load everything, render the entire graph, and display only what the height can display.

**Comment by lusingander** [comment]
Thanks for the report.

I understand that large repositories have issues, but it wasn't a priority. Due to the nature of the application, complex graphs will not fit on the terminal.
On the other hand, repositories with many commits but a simple graph should be better off being properly behaved.

**Comment by kdheepak** [comment]
After the change in #5 I'm not getting a stackoverflow but I am getting a different error:

<img width="563" alt="image" src="https://github.com/user-attachments/assets/e76951ba-a562-4652-a764-ab4b16aae8d6">

I think this is because you have `min_x` as `u8`. If you make that `u32` or `u64` you might not get the error. I would be possible to get the same graph to work with left and right scrolling. That'd be pretty awesome if it were to work.

**Comment by lusingander** [comment]
Thanks, I'm using `u8` for the reasons stated above.

Horizontal scrolling is certainly one option.
The way I thought of implementing this is to specify an offset and display only a part of the image.

However, the iTerm protocol does not have such a specification, and it just passes a base64 encoded string, so it seems that calculations would be required each time (it may be possible with the kitty protocol).

**Comment by kdheepak** [comment]
No worries! I have a patch that changes some `u8` to `usize` and it seems to work the same on small repos. On a repo the size of git it just hangs forever. I understand that's not a priority, though. I can close this issue!
