### ISSUE TITLE
State MSRV

### ISSUE THREAD

**Issue by 0323pin** [lusingander/serie#43]
Hi,

Would it be possible to add a `rust-version` line to `Cargo.toml` for easy monitoring the required MSRV?

**Reason**, I usually run on the latest stable Rust as I use x86_64 aka amd64 while NetBSD default version is usually latest stable -1 (or, sometimes -2) because, Rust bootstraps need to be generated for all the other supported platforms. This means, I usually don't know if a package will actually build with the default Rust version. Having MSRV helps here.

If it's not asking too much, it would help a bit. Thanks!

**Comment by lusingander** [comment]
Sounds good.

**Comment by 0323pin** [comment]
Perfect 🤗
